### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by tprelog** [cliviu74/scripts#1]
May I kindly suggest another approach to this line
https://github.com/cliviu74/scripts/blob/744ede9f53a43fc29677bd003ef197625e1f8cf0/home-assistant/homeassistant-install-freenas.csh#L20

Instead consider this option which will have the same effect to create configuration and finish installing without needing a timeout
```bash
# Creates the default configuration
hass --script ensure_config
# By running at this stage, homeassistant will finish the initial install
hass --script check_config
```

example running these commands manually ( from inside the activated venv ) to illustrate
```text
$ hass --script ensure_config
Creating directory /home/homeassistant/.homeassistant
Unable to find configuration. Creating default one in /home/homeassistant/.homeassistant
Configuration file: True

$ hass --script check_config
INFO:homeassistant.util.package:Attempting install of colorlog==4.1.0
Testing configuration at /home/homeassistant/.homeassistant
INFO:homeassistant.util.package:Attempting install of mutagen==1.44.0
INFO:homeassistant.util.package:Attempting install of aiohttp_cors==0.7.0
INFO:homeassistant.util.package:Attempting install of gTTS-token==1.1.3
INFO:homeassistant.util.package:Attempting install of defusedxml==0.6.0
INFO:homeassistant.util.package:Attempting install of netdisco==2.7.1
INFO:homeassistant.util.package:Attempting install of home-assistant-frontend==20200702.1
INFO:homeassistant.util.package:Attempting install of distro==1.5.0
INFO:homeassistant.util.package:Attempting install of PyNaCl==1.3.0
INFO:homeassistant.util.package:Attempting install of emoji==0.5.4
INFO:homeassistant.util.package:Attempting install of sqlalchemy==1.3.17
INFO:homeassistant.util.package:Attempting install of hass-nabucasa==0.34.7
```

**Comment by cliviu74** [comment]
Hey @tprelog nice one, thanks for the suggestion. 
I can't seem to find `ensure_config` option documented anywhere in the original hass documentation. Can you share a link to this option's doc?

**Comment by tprelog** [comment]
I can't find it either now in the current docs either... I did find a past reference to it here

https://github.com/home-assistant/home-assistant.io/blob/9d709051d9f828596810e4282a60b8898f4f3ca8/source/_docs/tools/scripts.markdown#-linkable_title-existance-of-configuration-

**Comment by cliviu74** [comment]
Cheers for looking @tprelog. 
Found a reference to the original PR https://github.com/home-assistant/core/pull/2548
I'll give it a go and check if that has the expected behaviour.

**Comment by cliviu74** [comment]
Works. Change is now merged, thanks for the suggestion @tprelog
